### ISSUE TITLE
Question about "Compactness 1"

### ISSUE THREAD

**Issue by kcy17** [vnarayan13/Slicer-OpenCAD#3]
Hi,
It is really nice to use the module you created!  I just have a question about the "Compactness 1" in "Heterogeneity CAD". According to the help page, it is supposed to be the ratio of volume to the (surface area)^(1.5). But as i look into the code in HeterogeneityCAD/FeatureExtractionLib/MorphologyStatistics.py 000

`def compactness1 (self, surfaceArea, volumeMM3):`
`return ( (volumeMM3) / ((surfaceArea)**(2/3.0) * math.sqrt(math.pi)) )`

I wonder if it should be (surfaceArea)**(3/2.0) instead.
Thanks for your time!

**Comment by vnarayan13** [comment]
Please See: https://github.com/Radiomics/pyradiomics
