### ISSUE TITLE
Question about "Spherical disproportion"

### ISSUE THREAD

**Issue by kcy17** [vnarayan13/Slicer-OpenCAD#4]
Hi,
I just have another question about the "Spherical disproportion" in "Heterogeneity CAD". According to the help page, it is supposed to be ratio of "the surface area of the image ROI" to "the surface area of a sphere with the same volume as the image ROI". But as i look into the code in HeterogeneityCAD/FeatureExtractionLib/MorphologyStatistics.py

`def sphericalDisproportion (self, surfaceArea, volumeMM3):`
`R = ( ( 0.75 * (volumeMM3) ) / (math.pi)**(1/3.0) )`
`return ( (surfaceArea)/(4*math.pi*(R**2)) )`

The volume of a sphere with radius "R" is (4/3) \* pi \* R^3.
In getting the "R" above, I wonder if it should be ( ( 0.75 \* (volumeMM3)  / (math.pi) )**(1/3.0) ) instead.
Thanks for your time!

**Comment by vnarayan13** [comment]
Please see: https://github.com/Radiomics/pyradiomics
